"""Criação inicial das tabelas de banco de dados

Revision ID: ed07dad03c7c
Revises: 
Create Date: 2024-08-16 13:20:14.788036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed07dad03c7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('horario', sa.String(length=20), nullable=False),
    sa.Column('data_agendamento', sa.Date(), nullable=False),
    sa.Column('tipo_volume', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('agendamentos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('is_cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cliente', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))

    op.create_table('agendamentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('horario', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('data_agendamento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('tipo_volume', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='agendamentos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agendamentos_pkey')
    )
    op.drop_table('agendamento')
    # ### end Alembic commands ###
